version: "2.2"

networks:
  mifos:
    driver: bridge
services:  
  mifos-app-server:
    image: com.mx.fintecheando.tomcat.mifosx.19.07
    restart: always
    ports:
      - 8444:8444
      - 8080:8080
    environment:
      - DRIVERCLASS_NAME=org.drizzle.jdbc.DrizzleDriver
      - PROTOCOL=jdbc
      - SUB_PROTOCOL=mysql:thin
      - fineract_tenants_driver=org.drizzle.jdbc.DrizzleDriver
      - fineract_tenants_url=jdbc:mysql:thin://fineractmysql:3306/fineract_tenants
      - fineract_tenants_uid=root
      - fineract_tenants_pwd=skdcnwauicn2ucnaecasdsajdnizucawencascdca 
      - FINERACT_DEFAULT_TENANTDB_HOSTNAME=fineractmysql
      - FINERACT_DEFAULT_TENANTDB_PORT=3306
      - FINERACT_DEFAULT_TENANTDB_UID=root
      - FINERACT_DEFAULT_TENANTDB_PWD=skdcnwauicn2ucnaecasdsajdnizucawencascdca
    # depends_on:
      # fineractmysql:
        # condition: service_healthy
      # mifos-sms-server:
        # condition: service_healthy
    healthcheck:
      test: curl -kfsS https://127.0.0.1:8443 | grep 'Tomcat' | wc -l 
      interval: 5s
      retries: 20        
  mifos-db-server:
    image: com.mx.fintecheando.mysql.mifosx.19.07
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test:  mysqladmin --user=root --password=mysql ping -h localhost
      interval: 5s
      retries: 20
    networks:
      - mifos  
  mifos-sms-server:
    image: com.mx.fintecheando.activemq.mifosx.19.07
    restart: always
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
    healthcheck:
      test:  curl -u admin:admin -s http://localhost:8161/admin
      interval: 5s
      retries: 20  
    networks:
      - mifos
